---
kind: pipeline
type: docker
name: default

steps:
  - name: jdk8_with_maven_3_9_0
    image: maven:3.9.0-eclipse-temurin-8
    commands:
      - mvn clean verify -X --no-transfer-progress

  - name: jdk11_with_maven_3_9_0
    image: maven:3.9.0-eclipse-temurin-11
    commands:
      - mvn clean verify --no-transfer-progress

  - name: jdk17_with_maven_3_9_0
    image: maven:3.9.0-eclipse-temurin-17
    commands:
      - mvn clean verify --no-transfer-progress

trigger:
  event:
    - push
    - pipeline
