name: Maven 3.9.x

on: [push]

jobs:
  jdk8:
    name: JDK 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set up Maven 3.9.0
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.0
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress verify
      - name: Set up Maven 3.9.1
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.1
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress verify

  jdk11:
    name: JDK 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Maven 3.9.0
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.0
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress verify
      - name: Set up Maven 3.9.1
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.1
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress verify

  jdk17:
    name: JDK 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven 3.9.0
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.0
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress verify
      - name: Set up Maven 3.9.1
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.1
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress verify

  wip:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven_version: [ "3.9.0", "3.9.1"]

    steps:
      - name: Set up Maven 3.9.0
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: ${{ matrix.maven_version }}
      - run: mvn --version

